### ISSUE TITLE
Error - Solved

### ISSUE THREAD

**Issue by ghost** [jkher/koala-pug#1]
![capture](https://cloud.githubusercontent.com/assets/10647023/19628438/73f6fd82-9966-11e6-8ef0-e6e08236ea5f.PNG)

Hi jkher, as you can see in the screenshot I am having this error, have you encountered this issue before? all I did is download your file and follow the instructions. Please help me. TIA

**Comment by jkher** [comment]
Hi cmcreativething, I don't see that issue on my environment. Having said that, you may want to try following troubleshooting:

Please close Koala application before you perform these steps.
1. Find out koala compiler installation directory. On my windows 10 environment it is under C:\Users\MY USER NAME\.koala\compilers\PugCompiler.
2. Delete "node_modules" folder.
3. Open command window (cmd) in PugCompiler folder.
4. run "npm install" to reinstall required modules. (Also, check if you see any error in command window while installing node_modules.

After you install required modules, see if you can compile .pug files from koala. Thanks.

**Comment by ghost** [comment]
Hi jkher,

Thanks for the response, I will try this after my work. I'll give you a feedback later, btw we have the same operating system.

**Comment by ghost** [comment]
Hi jkher,

Unfortunately, I don't have node_modules under pugcompiler folder. can you tell me how to download it without using cmd in windows. TIA

![capture2](https://cloud.githubusercontent.com/assets/10647023/19690633/ffc83aaa-9ad9-11e6-99e0-8a286f1db795.PNG)

**Comment by jkher** [comment]
Open dist folder.

Drag-and-drop koala-pug.koala-compiler on Koala application window.

**Comment by ghost** [comment]
![capture2](https://cloud.githubusercontent.com/assets/10647023/19828651/af0ed350-9dd4-11e6-9aec-b28f391ea7c2.PNG)
Hi jhker,

I still got that error. I uninstall the koala and drag-n-drop the pugcompiler but still got that error.

**Comment by ghost** [comment]
Hi jkher,

I just wanted you to know that I solved the issue, based on the instructions I should rename the extension file to .koala-compiler and I followed it. It was causing me error that is why I try to drag the file inside the dist folder and it works. Thanks for the plugin by the way.
